### PR TITLE
Mark blocks that branch off from a finalised block as discarded.

### PR DESCRIPTION
**Pull request by eulervoid**
## Purpose

This tackles Issue #28 and changes the visualization so that branches that start from an already finalized block a shown greyed out. 

## Changes

- Adds a function to recurse through the visualization tree and mark the appropriate blocks as discarded.
- Merged the lates master to this branch.
- Contains the changes from the `jp/treepacking` and `jp/treesorting` branches which contain work i did in January that seems not to have been merged yet. Sorry if this is a bit messy, i originally assumed they had already been merged when starting work on this.

### CODE REVIEW

**Comment by abizjak** [comment]
Thanks for this, but there is something gravely wrong with this PR.

There are changes in the diff that make no sense to be there, such as adding the changelog file, which is already on `main`, so it looks to me like there is some history disagreement.

Can you please clean that up? Otherwise this is not going to be possible to review.

Let me know if I can assist you with this in any way.

**Comment by eulervoid** [comment]
Hey thanks for getting back so quickly,
i agree that this is difficult to review, the reason is that it is not asking to merge to `main`, but to `jp/handle-discarded` which is a branch from when the repo was still on gitlab. The changes you are seeing are there because i merged the latest `main` to this branch to get it up to date, so a pull request against `main` should look a lot cleaner. Should i create that instead?

**Comment by abizjak** [comment]
Yes, please do.

Are there any branches that should be deleted in this repo that are made obsolete by this PR?

**Comment by eulervoid** [comment]
I created a pull request against main here: #48

**Pull request closed without merging**
